version: '3'
services:

  bot_redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  db:
    image: postgres
    restart: always
    env_file:
      - docker.env
    ports:
      - '5432:5432'

  tg_bot:
    build: .
    env_file:
      - docker.env
    depends_on:
      - bot_redis
      - db

